add agregate for transaction with user receipt
pagopa/pagopa-ecommerce-commons pull request #21
Opened 2023-01-27 09:31 UTC by ciuffagianluca

Add agregate for transaction with user receipt

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-02-01 08:26 UTC, giovanniberti approved these changes

2023-02-01 08:26 UTC, giovanniberti requested changes
Add tests 🙃

2023-02-02 08:38 UTC, ciuffagianluca commented
> Add tests 🙃

Tests added!

2023-02-02 08:55 UTC, giovanniberti approved these changes
Good job! 🚀

2023-02-02 09:26 UTC, merged