[CHK-3137] Remove xpay vpos business logic
pagopa/pagopa-ecommerce-commons pull request #216
Opened 2024-08-09 12:55 UTC by ciuffagianluca

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-28 13:51 UTC, pietro-tota submitted a review, later dismissed

2024-08-28 13:52 UTC, pietro-tota commented
Please add a brief PR description :)

2024-08-28 17:37 UTC, infantesimone requested changes
pay attention.
this common lib is also used by `helpdesk-service` to retrieve transaction info. With this PR if we update the common on `helpdesk-service` we no longer allow the recovery of vpos & xpay transactions? let's understand if we can proceed in this way

2024-08-29 12:19 UTC, ciuffagianluca commented
> pay attention. this common lib is also used by `helpdesk-service` to retrieve transaction info. With this PR if we update the common on `helpdesk-service` we no longer allow the recovery of vpos & xpay transactions? let's understand if we can proceed in this way

I restored all old pgs java files in order to make helpdesk running fine

2024-08-29 12:23 UTC, pietro-tota submitted a review, later dismissed

2024-08-29 13:04 UTC, pietro-tota approved these changes

2024-08-29 15:01 UTC, giovanniberti approved these changes

2024-09-04 13:38 UTC, merged