[CHK-951] Split authorization outcome event into a success and a failure event
pagopa/pagopa-ecommerce-commons pull request #22
Opened 2023-01-27 10:57 UTC by giovanniberti

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-02-02 13:13 UTC, infantesimone requested changes

2023-02-02 13:13 UTC, infantesimone commented on src/main/java/it/pagopa/ecommerce/commons/documents/TransactionAuthorizationFailedEvent.java
> +                TransactionEventCode.TRANSACTION_AUTHORIZED,
should be failed?

2023-02-02 13:25 UTC, giovanniberti commented on src/main/java/it/pagopa/ecommerce/commons/documents/TransactionAuthorizationFailedEvent.java
> +                TransactionEventCode.TRANSACTION_AUTHORIZED,
Definitely, fixed in d96d619

2023-02-07 16:07 UTC, pietro-tota approved these changes
Well done!

2023-02-08 08:03 UTC, merged