[CHK-1680] add pspOnUs flag
pagopa/pagopa-ecommerce-commons pull request #95
Opened 2023-07-05 12:30 UTC by ciuffagianluca

Add flag on transaction auth data to handle psp on us info 

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-10 07:06 UTC, infantesimone requested changes

2023-07-10 07:06 UTC, infantesimone commented on src/main/java/it/pagopa/ecommerce/commons/documents/v1/TransactionAuthorizationRequestData.java
> +    private boolean pspOnUs;
is a boolean, so better `isPspOnUs`?

2023-07-10 19:29 UTC, infantesimone approved these changes

2023-07-11 07:36 UTC, Fernando-Granato approved these changes

2023-07-11 12:16 UTC, pietro-tota commented
ping :) @ciuffagianluca

2023-07-11 15:06 UTC, merged